#comunicaçao com o banco de dados
spring:
datasource:
url:
jdbc: mariadb://localhost:3307/fornecedor
username: root
password: 12345
driver-class-name: org.mariadb.jdbc.Driver
jpa: 
hibernate: 
ddl-auto: create
